import React, { useState, useMemo } from 'react';
import { Activity, Search, Filter, Radio, CheckCircle2, AlertTriangle, RefreshCw, Cpu, Database, Satellite } from 'lucide-react';
import StatusBadge from '../components/StatusBadge';

export default function ActivityLogPage() {
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState('ALL');

  const logs = [
    { id: 'LOG-1092', timestamp: '18:52:10 UTC', event: 'Satellite image swath ingested', status: 'SUCCESS', source: 'INSAT-3D TIR-1 Channel', details: 'Full disc infrared frame ingested. Resolution: 4km.' },
    { id: 'LOG-1091', timestamp: '18:50:45 UTC', event: 'Cyclone detection model scan completed', status: 'SUCCESS', source: 'Vision Transformer ViT-B/16', details: 'Bounding box located at 15.40°N, 88.20°E. Confidence: 92.8%.' },
    { id: 'LOG-1090', timestamp: '18:48:22 UTC', event: 'Pattern classification executed', status: 'SUCCESS', source: 'Spatial Feature Classifier v2.1', details: 'Rapid Intensification Pattern identified. Eyewall organization score: 0.86.' },
    { id: 'LOG-1089', timestamp: '18:45:00 UTC', event: 'Trajectory prediction ensemble generated', status: 'SUCCESS', source: 'LSTM / Trajectory Transformer', details: '72-hour forecast path generated. 24h position: 17.10°N, 86.80°E.' },
    { id: 'LOG-1088', timestamp: '18:40:12 UTC', event: 'Critical system alert dispatched', status: 'WARNING', source: 'Alert Engine v1.4', details: 'Rapid Intensification Warning issued for Bay of Bengal SCS.' },
    { id: 'LOG-1087', timestamp: '18:35:50 UTC', event: 'Official bulletin report generated', status: 'SUCCESS', source: 'Report Generator Service', details: 'Cyclone Report CYC-2026-BOB-01-ADV-04 generated by Dr. A. Sharma.' },
    { id: 'LOG-1086', timestamp: '18:30:00 UTC', event: 'Data synchronization completed', status: 'SUCCESS', source: 'RealTime Sync Engine', details: 'Synchronized satellite telemetry swaths across 6 sensors.' },
    { id: 'LOG-1085', timestamp: '18:15:30 UTC', event: 'API fallback mode activated', status: 'FALLBACK', source: 'Frontend ApiClient Service', details: 'Backend API unreachable. Activated synthetic demo resilience stream.' }
  ];

  const filteredLogs = useMemo(() => {
    return logs.filter((log) => {
      const term = searchTerm.toLowerCase();
      const matchesSearch =
        !term ||
        log.event.toLowerCase().includes(term) ||
        log.source.toLowerCase().includes(term) ||
        log.details.toLowerCase().includes(term) ||
        log.id.toLowerCase().includes(term);

      const matchesStatus = statusFilter === 'ALL' || log.status === statusFilter;
      return matchesSearch && matchesStatus;
    });
  }, [searchTerm, statusFilter]);

  const getStatusBadge = (status) => {
    switch (status) {
      case 'SUCCESS':
        return <span className="px-2 py-0.5 rounded bg-emerald-950 text-emerald-400 border border-emerald-500/30 text-[10px] font-bold">SUCCESS</span>;
      case 'WARNING':
        return <span className="px-2 py-0.5 rounded bg-amber-950 text-amber-400 border border-amber-500/30 text-[10px] font-bold">WARNING</span>;
      case 'FALLBACK':
        return <span className="px-2 py-0.5 rounded bg-cyan-950 text-cyan-400 border border-cyan-500/30 text-[10px] font-bold">FALLBACK</span>;
      default:
        return <span className="px-2 py-0.5 rounded bg-blue-950 text-blue-300 border border-blue-800/30 text-[10px]">INFO</span>;
    }
  };

  return (
    <div className="p-4 lg:p-6 space-y-6 max-w-[1600px] mx-auto font-sans">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-blue-900/30 pb-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="font-heading font-extrabold text-2xl lg:text-3xl text-slate-100 tracking-tight">
              System Activity Log
            </h1>
            <StatusBadge status="ONLINE" label="LOG MONITORING ACTIVE" />
          </div>
          <p className="text-xs text-slate-400 font-mono mt-1">
            Real-time execution log recording satellite ingestion, model inference, alerts, and fallback events.
          </p>
        </div>

        <div className="flex items-center gap-3 bg-navy-900/80 px-4 py-2 rounded-xl border border-blue-800/30 text-xs font-mono text-slate-300">
          <Radio className="w-3.5 h-3.5 text-emerald-400 animate-pulse" />
          <span>LOG RETENTION: 30 DAYS</span>
        </div>
      </div>

      {/* Controls Bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 bg-navy-900/60 p-3 rounded-xl border border-blue-900/40 font-mono text-xs">
        <div className="flex items-center gap-2 flex-1 max-w-md bg-navy-950 px-3 py-1.5 rounded-lg border border-blue-900/30">
          <Search className="w-4 h-4 text-cyan-400 shrink-0" />
          <input
            type="text"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            placeholder="Search logs by event, model, or details..."
            className="w-full bg-transparent text-slate-100 placeholder-slate-500 focus:outline-none text-xs"
          />
        </div>

        <div className="flex items-center gap-2">
          <Filter className="w-3.5 h-3.5 text-cyan-400" />
          <span className="text-slate-400">Filter Status:</span>
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="bg-navy-950 border border-blue-800/40 rounded px-2.5 py-1 text-slate-200 focus:outline-none"
          >
            <option value="ALL">All Statuses</option>
            <option value="SUCCESS">SUCCESS</option>
            <option value="WARNING">WARNING</option>
            <option value="FALLBACK">FALLBACK</option>
          </select>
        </div>
      </div>

      {/* Logs Table */}
      <div className="overflow-x-auto rounded-xl border border-blue-900/30 glass-panel">
        <table className="w-full text-left font-mono text-xs border-collapse">
          <thead>
            <tr className="bg-navy-950 text-slate-400 border-b border-blue-900/40">
              <th className="p-3 uppercase">LOG ID & TIMESTAMP</th>
              <th className="p-3 uppercase">EVENT NAME</th>
              <th className="p-3 uppercase">STATUS</th>
              <th className="p-3 uppercase">SOURCE MODULE</th>
              <th className="p-3 uppercase">EVENT DETAILS</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-blue-900/30 bg-navy-900/40 text-slate-200">
            {filteredLogs.length === 0 ? (
              <tr>
                <td colSpan={5} className="p-8 text-center text-slate-500">
                  No activity log entries match query "{searchTerm}".
                </td>
              </tr>
            ) : (
              filteredLogs.map((log) => (
                <tr key={log.id} className="hover:bg-navy-850/60 transition-colors">
                  <td className="p-3 text-cyan-400 font-bold">
                    {log.id}
                    <span className="text-slate-400 text-[10px] block font-normal">{log.timestamp}</span>
                  </td>
                  <td className="p-3 font-sans font-bold text-slate-100">{log.event}</td>
                  <td className="p-3">{getStatusBadge(log.status)}</td>
                  <td className="p-3 text-slate-300">{log.source}</td>
                  <td className="p-3 text-slate-400 text-[11px] font-sans">{log.details}</td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
